apiVersion: apps/v1
kind: Deployment                      #it is of type service denoted by the kind field
metadata:
  name: jenkins                       #name of the service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.60.3    #name of the image with the version
        ports:
        - containerPort: 8089          