apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32766
  externalIPs:
    - 192.168.0.1   
  # When the node receives a request on the static port (32766)
  # select pods with the label 'app' 
  selector:
    app: jenkins